name: Build and Push to Amazon ECR

on:
  push:
    branches: [ "master" ]   # adjust branch as needed

permissions:
  id-token: write   # required for OIDC
  contents: read    # required to checkout code

jobs:
  build-and-push:
    # Instead of ubuntu-latest, point to your self-hosted runner
    runs-on: git-runner-scale-set-gke
    # optionally, if you’ve given your runner custom labels, you can be more specific:
    # runs-on: [self-hosted, linux, x64]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::050451400373:role/Github-ECS-cicd-role
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: surajkamble432
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
