name: Deploy Code

on:
  push:
    branches:
      - DEV  # Runs when you push to main branch

jobs:
  deploy:
    runs-on: ip-172-31-40-44   # Use your EC2 runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy code to target path
        run: |
          hostname
          mkdir -p /home/ec2-user/pfl-appliction
          rm -rf /home/ec2-user/pfl-appliction/*
          cp -r ./* /home/ec2-user/pfl-appliction/
